# Generated by Django 5.0.6 on 2024-08-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='Number',
            field=models.IntegerField(max_length=10),
        ),
    ]
