# Generated by Django 5.0.6 on 2024-08-04 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0003_alter_book_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=15)),
                ('Description', models.TextField()),
                ('Rating', models.IntegerField()),
                ('Image', models.ImageField(blank=True, upload_to='items/')),
            ],
        ),
        migrations.AddField(
            model_name='itemlist',
            name='Category_name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=15)),
                ('description', models.ImageField(upload_to='')),
                ('Price', models.ImageField(upload_to='')),
                ('Image', models.ImageField(upload_to='items/')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='Home_App.itemlist')),
            ],
        ),
    ]
