# Generated by Django 5.0.6 on 2024-08-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0004_aboutus_feedback_itemlist_category_name_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(),
        ),
    ]
