# Generated by Django 5.0.6 on 2024-08-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0007_itemlist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='Category_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='items',
            name='Item_name',
            field=models.CharField(max_length=30),
        ),
    ]
